### PR TITLE
Pyproject toml setup

### LINKED ISSUE #298: Legacy Editable Install Deprecation
Highlighted by @Ulvetanna on #294, the way we currently package PolarRoute is now deprecated and will stop working from Pip version 25 (early next year). 

Screenshot 2024-09-26 at 07 56 41

To fix this we need to include a `pyproject.toml` file and make sure this works with our existing `setup.py` file or make any necessary changes to update this. 

Useful links: 

- https://github.com/pypa/pip/issues/11457

- https://ichard26.github.io/blog/2024/08/whats-new-in-pip-24.2/#legacy-editable-installs-are-deprecated

### PR DESCRIPTION
**Pull request by gecoombs**
# PolarRoute Pull Request 

Date: 03/10/24
Version Number: 1.0.0
 
## Description of change
Change from using setup.py to pyproject.toml in order to maintain compatibility with future versions of pip. I've also updated some of the classifiers and added a few keywords, open to suggestions for changes/additions.

It would be good if you could try creating a new virtual environment and installing PolarRoute with this branch to test the changes.

## Fixes #298 

# Testing

- [x] My changes have not altered any of the files listed in the testing strategy

Files changes:
```
pyproject.toml
setup.py
tests/requirements.txt
```

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [x] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [x] My PR has been made to the `0.6.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

### CODE REVIEW

**Review by Ulvetanna — APPROVED** [review]
Great !! :) 

I assume nothing needs to change for the instillation in the README.md ?

**Comment by gecoombs** [comment]
I've put this PR into the dev branch since that still hasn't been approved to merge but I'm also happy for these changes to wait until after the refactor release to be applied as a hotfix.

**Comment by gecoombs** [comment]
> Great !! :)
> 
> I assume nothing needs to change for the instillation in the README.md ?

The install process is the same but it would be good for others to test it quickly (especially on a different OS to me) to check it still works as before.

**Review by SamuelHall700 — APPROVED** [review]
I've tried installing into a fresh venv and everything works just fine still, including the tests. Good to get this one in before it becomes depricated :D!

**Pull request merged**
