### PR TITLE
Final mesh refactor

### PR DESCRIPTION
**Pull request by hjabbot**
Refactoring of the mesh generation code has been completed! The code has been updated to be more object-oriented, and bugs have been caught and noted for future patching (not implemented yet as regression tests had to pass).

As well as this, there is a new suite of docs. The old docs have been updated with the instructions of creating configs in the new format, and creation of new dataloaders has been detailed. UML and sequence diagrams have been added describing the processing required for the mesh construction.  

image

All regression tests have passed, dump attached below
[mesh_refactor_output.txt](https://github.com/antarctica/PolarRoute/files/10885065/mesh_refactor_output.txt)

### CODE REVIEW

**Review by Ulvetanna — CHANGES_REQUESTED** [review]
Currently issue with merging of some of the vehicle properties. Make sure that you inherit recent updates from George currently on integration testing.

Once that is complete data_loaders.py has a merge issue. Double check this is ok.

**Review by SamuelHall700 — CHANGES_REQUESTED** [review]
Most of the tests files are reporting very large numbers of changed lines - basically the entire file. It should be the case that only the configuration section of these files have changed. The cause of this is most likely that on in intergration_testing branch _most_ of the test files are un-formatted, while _most_ of the test files are formatted in the mesh redesign.

I've created a pull request into intergration_testing for format all the the test files, which should fix this issue. I've request @Ulvetanna for review. https://github.com/antarctica/PolarRoute/pull/139 

@ayat-khairy or @hjabbot can you pull the reformatted test files into the final-mesh-refactor branch one they're merged?

The merge conflict in dataloader.py is coming from the addition of GRF dataloader that Jonny has created since the start of the mesh re-architecture, I've created as issue around it here: #117

**Comment by SamuelHall700** [comment]
@ayat-khairy , @hjabbot I've pushed a change to integration_testing to format all the test files. If these changes are pulled into final-mesh-refactor it should solve most of the merge conflicts :)

**Review by Ulvetanna — APPROVED** [review]
Looks legit

**Review by SamuelHall700 — APPROVED** [review]
Looks good, @hjabbot or @ayat-khairy , feel free to press the button!

**Review by SamuelHall700 — CHANGES_REQUESTED** [review]
Can testing.ipynb to removed from the repo?

**Review by SamuelHall700 — APPROVED** [review]

**Pull request merged**
